version: "2"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./src/database:/src/database/
    ports:
      - "27017:27017"